"""empty message

Revision ID: dc02dd97d98d
Revises: f6112d375a54
Create Date: 2025-01-09 15:49:06.784505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc02dd97d98d'
down_revision: Union[str, None] = 'f6112d375a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author_id', sa.Integer(), nullable=False))
    op.drop_constraint('article_user_id_fkey', 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'user', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('article', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key('article_user_id_fkey', 'article', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('article', 'author_id')
    # ### end Alembic commands ###
