"""empty message

Revision ID: f6112d375a54
Revises: dc8afac27565
Create Date: 2025-01-09 15:45:53.062161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6112d375a54'
down_revision: Union[str, None] = 'dc8afac27565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'article', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'category_id')
    # ### end Alembic commands ###
